# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Daniel Arriola
title: Daniel Arriola
email: dannielarriola@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: http://dannielarriola.github.io # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: dannielarriola
github_username:  dannielarriola
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/daniel-arriola-37826454/

# Address information
address_street: ""
address_city: Buenos Aires
address_state: CA
address_zip: 1765

# Build settings
markdown: kramdown
