baseURL = "https://dannielarriola.github.io/"
languageCode = "es-ar"
title = "Daniel Arriola"
theme = "hugomaterialize"
publishDir = "./docs"
[params]
description = "Web Developer"
githuburl = "https://github.com/dannielarriola"
twitterurl = "https://twitter.com/dannielarriola"
linkedinurl = "https://www.linkedin.com/in/daniel-arriola-37826454/"
mail = "dannielarriola@gmail.com"
